# Parma Light Configuration

# data storage
[store]
entity_store = "/app/datastore_parma/entity_store"
data_dir = "/app/datastore_parma/data_dir"
temp_dir = "/app/datastore_parma/temp_dir"

# Server configuration
[server]
host = "0.0.0.0"
port = 8080

# for server select:
#   "waitress", WSGI server for windows & linux, fully Python
#   "development", local debugging, debugger with breakpoints behave strange
#   "development_debug", flask with debug=True, debugger with breakpoints work, 
#                        but note: sequential execution, one flask request after the previous terminated
# you cannot use gunicorn (it uses worker processes and not worker threads). Currently We need sharing of data structures.
server = "waitress"

# Logging configuration
[logging]
level = "INFO"
file = "/app/parma_light.log"

# History of user commands issued in the frontend
[history]
file = "parma_light_cli_history"